### ISSUE TITLE
Would you give me some adevice?

### ISSUE THREAD

**Issue by hwtang1979** [pratikfarkase94/Touch-Screen-based-fully-Digital-Instrument-cluster-Using-Raspberry-Pi-3-and-CPP-QT-QML#1]
Hi,
Would you tell me how to compile this dashboard for rpi3 (especially compile qt5) and deploy it on rpi3?
Thanks a lot!

**Comment by pratikfarkase94** [comment]
Hi. Do u want to compile this on the pie itself or set up a cross
development environment and then deploy it on the target? If you plan to
compile and run the code on pie, then its a straight forward process. All
you have to do is install qt 5 libraries, qmake etc. But if you want to try
the second method then i can guide you

**Comment by hwtang1979** [comment]
Hi,
Thank you for your answer. Sorry to response so late.
I already compiled and run it successfully on my PC which run ubuntu 18.04. However, I found that this application was based on X11, and it appeared as a window on my PC. That was not what I want. I want that instrument cluster is not a window, just like your demo on rpi3. So, now I want to cross-compile it on my PC and run it on rpi3. That's great that you can guide me. If you would, you could email me, my email is cs.hongweitang@gmail.com.
Thanks again!
